### PR TITLE
remove broken quarkus testing workflow

### PR DESCRIPTION
**Pull request by tilokowalski**

### CODE REVIEW

**Comment by hown3d** [comment]
Wouldn't it be easier to just disable tests that are failing for now?
#1 will implement tests. I think removing this workflow completly is not the right move.

**Comment by joshuamerold** [comment]
> Wouldn't it be easier to just disable tests that are failing for now? #1 will implement tests. I think removing this workflow completly is not the right move.

I think so too. `SpotifyTest#getPlayHistoryListens30Days` should be disabled due to expiration of the api key

**Comment by tilokowalski** [comment]
> Wouldn't it be easier to just disable tests that are failing for now? #1 will implement tests. I think removing this workflow completly is not the right move.

Of course, it would be better to have a functioning test workflow.

However this workflow does not fail the expected way (due to unit test failure), but rather it is a problem of Quarkus tests, where there is no automatic script termination, but it waits for user input. That's why, for example, the workflow ran for over 6 hours before it was automatically canceled.

In a scenario where the script is terminated after the tests are run (no matter the outcome), the workflow would be great as it is now, but as it works, it is pointless.

Alternatively, to removing it, rebuilding it into a terminating script would be an option, but as a hotfix, I had considered removing it, hence why i opened the PR.

**Comment by joshuamerold** [comment]
Have a look at #1: The latest changes (running the workflow with `mvn verfiy`) allow the tests to run successfully.

**Pull request closed without merging**
